                </div>
              <div id="right">
                    <ul id="box">
                    	<li>
                    		<h3>Quick Links</h3>
                            <p>
                            &raquo; <a href="index.asp">Search</a><br />
                            &raquo; <a href="apartments.asp">Apartment Complexes</a><br />
                            &raquo; <a href="advertise.asp">Post</a><br />
                            &raquo; <a href="roommates.asp">Find Roommates</a><br />
                            &raquo; <a href="resources.asp">OCH Resources</a><br />
                            &raquo; <a href="contact.asp">Contact Us</a><br />
                            </p>
                                                       
                        </li>
                    </ul>
                </div>
		<iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2F86432701808&width=600&colorscheme=light&show_faces=true&border_color&stream=true&header=true&height=435" scrolling="yes" frameborder="0" style="border:none; overflow:hidden; width:350px; height:435px; background: white; float:right; " allowtransparency="true">
</iframe>
                <div id="clear"></div>
            </div>
            <div id="footer">
                <a href="http://www.facebook.com/pages/Sub-Board-I-Inc/86432701808" target="_blank"><img src="../images/facebook.png" border="0" width="18" height="18" title="Like SBI on Facebook!" alt="Like SBI on Facebook" /></a>&nbsp;&nbsp;<a href="http://twitter.com/ub_sbi" target="_blank"><img src="../images/twitter.png" border="0" width="18" height="18" title="Follow SBI on Twitter!" alt="Follow SBI on Twitter" /></a><br /><br />
                <strong>DEPARTMENTS</strong><br />
                <a href="http://www.ubgeneration.com/">Generation</a>&nbsp;-&nbsp;
        		<a href="http://www.sbi-clinicallab.buffalo.edu/">Clinical Lab</a>&nbsp;-&nbsp;
        		<a href="http://www.sbihealtheducation.org/">Health Education</a>&nbsp;-&nbsp;
        		<a href="http://www.healthinsurance.buffalo.edu/">Student Medical Insurance</a>&nbsp;-&nbsp;
        		<a href="http://www.sbi-pharmacy.buffalo.edu/">Pharmacy</a><br />
                <a href="http://www.wrub.org/">WRUB</a>&nbsp;-&nbsp;
        		<a href="http://www.legalassistance.buffalo.edu/">Legal Assistance</a>&nbsp;-&nbsp;
        		<a href="http://www.offcampushousing.buffalo.edu/">Off-Campus Housing</a>&nbsp;-&nbsp;
        		<a href="http://www.subboard.com/tickets/">Ticket Office</a>&nbsp;-&nbsp;
        		<a href="http://www.sbi-accounting.buffalo.edu/">Accounting</a><br />
        		<a href="disclaimer.asp">Disclaimer</a><br /><br />
                Student Owned and Operated by <a href="http://www.subboard.com/">Sub-Board I, Inc.</a> <a href="http://www.subboard.com/contact.php">Contact Us</a><br /><br />
                &copy; 2012 Sub Board I. Incorporated
                <div id="clear"></div>
            </div>
        </div>
    </body>
</html>