<html lang='en-us'>
	<head>
        <title>Sub Board I: Off-Campus Housing - University at Buffalo</title>
        <script type='text/javascript' src='../js/jquery.js'></script>
        <script type='text/javascript' src='http://code.jquery.com/ui/1.10.3/jquery-ui.js'></script>
        <script type='text/javascript' src='../js/jquery.simplemodal.js'></script>
        <script type='text/javascript' src='../js/basic.js'></script>
        <link type='text/css' href='css/och.css' rel='stylesheet' media='screen' />
        <link type='text/css' href='../css/basic.css' rel='stylesheet' media='screen' />
        <link type='text/css' href='http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css' rel='stylesheet' media='screen' />
        <script language="javascript">
        function checkCheckBox(f) {
            if(!f.agree.checked) {
                alert('Please check the box to continue.');
                return false;
            }
            else return true;
        }
        </script>
	</head>
	<body>
        <div id="container">
            <div id="header">
                <div id="logo"><a  href="http://www.subboard.com/och/new/" ><img src="../images/logo.jpg" /></a></div>
                <div id="search">
                    <form id="search" action="http://search.buffalo.edu/search">
                    <input type="text" name="q" id="q" placeholder="Search SubBoard.Com" />
                    <input type="hidden" name="client" value="UB" />
                    <input type="hidden" name="proxystylesheet" value="UB" />
                    <input type="hidden" name="output" value="xml_no_dtd" />
                    <input type="hidden" name="site" value="UB" />
                    <input type="hidden" name="as_sitesearch" value="http://subboard.com" />
                    </form>
                </div>
                <div id="navigation">
                    <ul id="menu" style="float:right;">
                        <li><a href="index.asp">Search</a></li>
                        <li><a href="advertise.asp">Advertise</a></li>
                        <li><a href="roommates.asp">Roommates</a></li>
                        <li><a href="resources.asp">Resources</a></li>
                        <li><a href="contact.asp">Contact Us</a></li>
                    </ul>
                    <div id="clear"></div>
                </div>
            </div>
            <div id="vector">
                <div id="slider"><img src="../images/image1.jpg" width="940px" height="216px" /></div>
                <div id="clear"></div>
            </div>
            <div id="wrapper">
                <div id="left">