<div id="container">
            <div id="header">
                <div id="logo"><img src="../images/logo.jpg" /></div>
                <div id="search">
                    <form id="search" action="http://search.buffalo.edu/search">
                    <input type="text" name="q" id="q" placeholder="Search SubBoard.Com" />
                    <input type="hidden" name="client" value="UB" />
                    <input type="hidden" name="proxystylesheet" value="UB" />
                    <input type="hidden" name="output" value="xml_no_dtd" />
                    <input type="hidden" name="site" value="UB" />
                    <input type="hidden" name="as_sitesearch" value="http://subboard.com" />
                    </form>
                </div>
                <div id="navigation">
                    <ul id="menu">
                        <li><a href="index.asp">Search</a></li>
                        <li><a href="advertise.asp">Advertise</a></li>
                        <li><a href="roommates.asp">Roommates</a></li>
                        <li><a href="resources.asp">Resources</a></li>
                        <li><a href="contact.asp">Contact Us</a></li>
                    </ul>
                    <div id="clear"></div>
                </div>
            </div>
            <div id="vector">
                <div id="slider"><img src="../images/image1.jpg" width="940px" height="216px" /></div>
                <div id="clear"></div>
            </div>
            <div id="wrapper">
                <div id="left">