		<div class='table_layout_wrapper'>
			<ul id='categories'>
				<li class='category-home'><a href='/index.asp' <% Current category, "Home" %>>Home</a></li>
				<li class='category-calendar'><a href='/calendar.asp' <% Current category, "Calendar" %>>Events</a></li>
				<li class='category-jobs'><a href='/jobs.asp' <% Current category, "Jobs" %>>Jobs</a></li>
				<li class='category-about_us'><a href='/about_us.asp' <% Current category, "About Us" %>>About Us</a></li>
				<li class='category-contact'><a href='/contact.asp' <% Current category, "Contact" %>>Contact</a></li>
			</ul>
		</div>