		<div id='footer'>
			<!--<div id='footer_home_link'><a href='/'>SBI student-owned services</a></div>
			
			<ul class='divisions n1'>
				<li class='n1'><a href='http://www.ubgeneration.com'>Generation</a></li>
				<li class='n2'><a href='http://www.sbi-clinicallab.buffalo.edu/'>Clinical Lab</a></li>
				<li class='n3'><a href='http://sbihealtheducation.org/'>Health Education</a></li>
				<li class='n4'><a href='http://www.healthinsurance.buffalo.edu/'>Student Medical Insurance</a></li>
				<li class='n5'><a href='http://www.sbi-pharmacy.buffalo.edu/'>Pharmacy</a></li>
			</ul>
			
			<ul class='divisions n2'>
				<li class='n1'><a href='http://www.wrub.org'>WRUB</a></li>
				<li class='n2'><a href='http://www.legalassistance.buffalo.edu/'>Legal Assistance</a></li>
				<li class='n3'><a href='http://www.offcampushousing.buffalo.edu/'>Off-Campus Housing</a></li>
				<li class='n4'><a href='/tickets'>Ticket Office</a></li>
				<li class='n5'><a href='http://www.sbi-accounting.buffalo.edu/'>Accounting</a></li>
			</ul>
		</div>-->
		<div id='byline'>Student Owned and Operated by <a href='/'>Sub-Board I, Inc</a>. <!--<a href='/contact.asp'>Contact SBI</a>--></div>