		<meta http-equiv='Content-type' content='text/html; charset=utf-8'>
		<title>Sub Board I, Inc &mdash; <% Print iif(subcategory, subcategory, category) %></title>
		
		<link rel='stylesheet' href='/resources/stylesheets/reset.css' type='text/css' charset='utf-8'>
		<link rel='stylesheet' href='/resources/stylesheets/style.css' type='text/css' charset='utf-8'>
		
		<!--[if ie]><link rel='stylesheet' href='/resources/stylesheets/ie.css' type='text/css' charset='utf-8'><![endif]-->