		<meta http-equiv='Content-type' content='text/html; charset=utf-8'>
		<title><% Print iif(subcategory, subcategory, category) %></title>
		
		<link rel='stylesheet' href='/resources/stylesheets/reset.css' type='text/css' charset='utf-8'>
		<link rel='stylesheet' href='/resources/stylesheets/default-revised.css' type='text/css' charset='utf-8'>
		<!--[if IE]>
			<link rel='stylesheet' href='/resources/stylesheets/ie-revised.css' type='text/css' charset='utf-8'>
		<![endif]-->
		
		<script type='text/javascript' src='/resources/scripts/navigation_menu.js'></script>