		<div id='header'>
			<h1><a href='/' class='image-replacement'>Sub-Board I</a></h1>
			
			<h2><a href='http://www.healtheducation.buffalo.edu/' class='image-replacement'>HealthEducation.<span class='domain'>buffalo.edu</span></a></h2>
			
			<form method='get' action='../sbiDropDown.asp' id='form1' name='form1'>
				<p>
					<select name='sbiDropDown' onchange='go_to(this.form.sbiDropDown);'>
						<option value='http://subboard.com'>Student Owned Services</option>
						
						<option value='http://www.wrub.buffalo.edu'>WRUB</option>
						<option value='http://www.sbi-clinicalLab.buffalo.edu'>Clinical Lab</option>
						<option value='http://www.healtheducation.buffalo.edu'>Health Education</option>
						<option value='http://www.sbi-pharmacy.buffalo.edu'>Pharmacy</option>
						<option value='http://www.healthinsurance.buffalo.edu'>Student Medical Insurance</option>
						<option value='http://www.legalAssistance.buffalo.edu'>Legal Assistance</option>
						<option value='http://www.offCampusHousing.buffalo.edu'>Off-Campus Housing</option>
						<option value='http://www.sbi-ticketoffice.buffalo.edu'>Ticket Office</option>
					</select>
				</p>
				<noscript>
					<p><input type='submit' value='Go' class='formButton' id='submit1' name='submit1'></p>
				</noscript>
			</form>
		</div>