		<meta http-equiv='Content-type' content='text/html; charset=iso-8859-1'>
		<title>Off-Campus Housing and Apartments at UB &mdash; <% Print iif(subcategory, subcategory, category) %></title>
		
		<link rel='stylesheet' href='/resources/stylesheets/reset.css' type='text/css' charset='utf-8'>
		<link rel='stylesheet' href='/resources/stylesheets/style.css' type='text/css' charset='utf-8'>
		
		<!--[if ie]><link rel='stylesheet' href='/resources/stylesheets/ie.css' type='text/css' charset='utf-8'><![endif]-->
		
		<link rel='stylesheet' href='/och/resources/stylesheets/style.css' type='text/css' charset='utf-8'>