			<h4>Quick Links</h4>
			<ul class='links'>
				<li><a href='index.asp'>Search</a></li>
				<li><a href='apartments.asp'>Apartment Complexes</a></li>
				<li><a href='advertise.asp'>Post</a></li>
				<li><a href='roommates.asp'>Find Roommates</a></li>
				<li><a href='resources.asp'>OCH Resources</a>
					<ul style='margin: 0 0 0 1em'>
						<li><a href='resources.asp#quick_tips'>Renter Quick Tips</a></li>
						<li><a href='resources.asp#directory'>Directory</a></li>
						<li><a href='resources.asp#email_notifications'>Email Notifications</a></li>
						
					</ul>
				</li>
				
				<li><a href='contact.asp'>Contact Us</a></li><br><br>

				<li><a href='http://subboard.com/pharmacy'><img src='/och/resources/images/ads/viewer.png' width="85%"></a></li>
			</ul>